# Generated by Django 2.2 on 2019-05-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_adverts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adverts',
            options={'verbose_name_plural': 'Adverts'},
        ),
    ]
