# Generated by Django 2.2 on 2019-05-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190516_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
