# Generated by Django 2.2 on 2019-06-17 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190527_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('images', models.ImageField(upload_to='images/')),
                ('author', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
